### ISSUE TITLE
Use sessions in redis

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#102]
Get the session key from the cookie `OpenSlidesSessionID`. Append the prefix `session:` to it and query this key from redis. If it does not exist assume user id 0. if it exists, b64 decode the string. It has the form `<hash>:{'_auth_user_id': '1', ...<more data>}`.

Example:

I have the key `session:jdlh3s53vaa6bvnh7jcu9tdof0pdtp5j` in redis with the content `ODFiMzYxMWQ1NDhmZTNjOWZmYmRhMDViMGFiMjQyNDM0OGIxNDJlMDp7Il9hdXRoX3VzZXJfaWQiOiIxIiwiX2F1dGhfdXNlcl9iYWNrZW5kIjoiZGphbmdvLmNvbnRyaWIuYXV0aC5iYWNrZW5kcy5Nb2RlbEJhY2tlbmQiLCJfYXV0aF91c2VyX2hhc2giOiI5YjZjNmU5YWJkMGQ3OGVmMzc3MmQ0NGNkMDljMTRmNWRlOWE0NTI1In0=`. B64 Decoded: `81b3611d548fe3c9ffbda05b0ab2424348b142e0:{"_auth_user_id":"1","_auth_user_backend":"django.contrib.auth.backends.ModelBackend","_auth_user_hash":"9b6c6e9abd0d78ef3772d44cd09c14f5de9a4525"}`

Split it on the first colon. Build the hash from the second part (https://github.com/django/django/blob/2.2.17/django/contrib/sessions/backends/base.py#L103) and compare with the given hash.

If anything goes wrong (decoding failure, bad hash, ...) assume user id 0. If the hash is ok, get the user id from the JSON object.

Hashing:

[this method](https://github.com/django/django/blob/2.2.17/django/utils/crypto.py#L23) is used for hashing. The key_salt is the string `openslides.utils.sessions.SessionStore`. You need the secret key, which is a string, too.

Env-variables:

Please accept `COOKIE_NAME`, `SESSION_PREFIX` and `SECRET_KEY` as env variables.

**Comment by FinnStutzenstein** [comment]
This PR fixes the server implementation to a controlled behavior by ourselfs: https://github.com/OpenSlides/OpenSlides/pull/5850

**Comment by ostcar** [comment]
PRs are merged
