### ISSUE TITLE
Missing autoupdate after permission change can_be_speaker

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides3-autoupdate-service#132]
Adding permission "can_be_speaker" does not change anything in client (reload required to get "Add me" button in list of speakers).

**Comment by FinnStutzenstein** [comment]
I cannot reproduce this. Do you have a way of doing it?

**Comment by emanuelschuetze** [comment]
Fixed with https://github.com/OpenSlides/OpenSlides/pull/5935
