### ISSUE TITLE
recommendation referenced motions do not work on a motion block slide.

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#151]
There is a spelling mistake here: https://github.com/OpenSlides/openslides3-autoupdate-service/blob/master/internal/apps/motion/projector.go#L215

Also check for other places with the same mistake

**Comment by ostcar** [comment]
I don't get it.

Could you give me a full bug report? What did you do, what happened, what did you expect.

Could you also tell me what spelling is wrong in the given line? The line is only for debugging. I don't understand, how it cause a bug.

**Comment by FinnStutzenstein** [comment]
It should be `recommendation.show_extension` instead of `recommeendation.show_extension`.

>  The line is only for debugging. I don't understand, how it cause a bug.

Ah ok, I assumed, that this may cause a bug. You can close it if you want.

**Comment by ostcar** [comment]
I will fix the spelling mistake.

I will also rename "con" to something like "debug" to make it clear what this object is about.
