### ISSUE TITLE
Quotations in user names raises errors

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#170]
When projecting a user with the structure level `y"x` this error appears:

```
Error updating projector slides in the data cache: decoding projector elements json: error calling MarshalJSON for type json.RawMessage: invalid character 'y' after object key:value pair
```

I observed the error in our prod-logs. It seems, that the username is not json-encoded [here](https://github.com/OpenSlides/openslides3-autoupdate-service/blob/master/internal/apps/user/projector.go#L38). Are there more places where raw values are put into a json structure?

**Comment by ostcar** [comment]
This is a very stupid mistake on me side.

I am not sure if there are more places like it.

 I was assuming, that usernames only contain letters that are valid in a JSON string.

Do we have a document that says what letters are allowed? Do we have a documentation like this for OS4?

**Comment by FinnStutzenstein** [comment]
Only implicit: Everything is allowed.

**Comment by ostcar** [comment]
I used different search patterns to find similar errors and could only find the username. I hope #171 fixes all of them
