### ISSUE TITLE
Ensure Cache on startup

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides3-autoupdate-service#18]
When the service starts, there needs to be a redis key that tells the service, that the cache if ready.

@FinnStutzenstein Could you create such a key and tell me the name and value?

**Comment by FinnStutzenstein** [comment]
I added the key `cache_ready`. If it is present, the cache is ready.

**Comment by ostcar** [comment]
Should be work now.

It tests, that the key exists. If not, it tries again after one second. If it exist and the value is not "ok", the service stops with an error message.

If the worker fails to create the cache, it would be a good thing to write an error message inside "cache_ready" so the autoupdate-service stops.
