### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides3-autoupdate-service#181]
Starting autoupdate service from current master failed with error:
```
panic: runtime error: invalid memory address or nil pointer dereference
signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x860dfe]
```
caused by commit 0c7fc3c7caf70b974e721f072ba569ce4d762593

**Comment by emanuelschuetze** [comment]
@ostcar ping

**Comment by emanuelschuetze** [comment]
Should we wait with our 3.4 release for your fix?

**Comment by ostcar** [comment]
Either wait or use the last commit. When do you need it?

**Comment by ostcar** [comment]
@emanuelschuetze should be fixed. Please test again
