### ISSUE TITLE
Restricters

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#24]
Assignment polls:
- [x] `amount_global_abstain` and `amount_global_no` are not removed (the `votes_*` are correctly removed)

Assignment option:
- [x] `yes`, `no`, `abstain` must be removed when not published and no manage perms

Mediafiles:
- [x] a non admin does not see anything. The permission must be `mediafiles.can_see`: https://github.com/OpenSlides/openslides3-autoupdate-service/blob/master/internal/restricter/mediafile/mediafile.go#L11
- [x] `Can not restrict key mediafiles/mediafile:3 for user 2: invalid type []interface {} for mediafile.inherited_access_groups_id`, if e.g. `inherited_access_groups_id` is `[2]`.

RequiredUsers:
- [x] The permission for speakers is wrong. It must be `agenda.can_see_list_of_speakers`: https://github.com/OpenSlides/openslides3-autoupdate-service/blob/57eb957248cfa12de1390ccb8995ef76cbfd9358/internal/restricter/agenda/agenda.go#L86

Regarding the assignment-* models: I did not check motions, but this should be the same behavior

**Comment by ostcar** [comment]
I forgot to remove the "additional_fields". The amount_global_abstain and amount_global_no seems to be the only cases: https://github.com/OpenSlides/OpenSlides/blob/b712af2d6dc4ccd0b0e35cbc6a2a82964fb363a0/openslides/assignments/access_permissions.py#L20

On Assignment option I did a wrong copy and paste: https://github.com/OpenSlides/openslides3-autoupdate-service/blob/master/internal/restricter/poll/poll.go#L81

@FinnStutzenstein Why to you think, that a non admon does not see anything on Assignment option? In the python code, it seems, that a non admin can see everything on a published option and only some fields are removed on non published options: https://github.com/OpenSlides/OpenSlides/blob/master/openslides/poll/access_permissions.py#L33

**Comment by FinnStutzenstein** [comment]
> Why to you think, that a non admins does not see anything on Assignment option?

This was a misformatting of the issue: THis belogs to the `mediafile` section.

There are some other small issues left.

**Comment by ostcar** [comment]
I fixed the other issues. If you found more bugs that throw an error, then please paste the full_data ob the object and the expected restricted value. Then I can write a test to make sure the bug is fixed.

**Comment by ostcar** [comment]
I close this issue since there is nothing else to do here. If you find more bug, please open new issues.
