### ISSUE TITLE
Notify is missing `name`

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#31]
The `name` key in the notify request and notify message is missing. This is used to dispatch the message in the client. It is required and must be a non-empty string. This has to be validated in the server, so no malformed messages can be send.

**Comment by ostcar** [comment]
I thought you could be a required field inside the message. I don't think it has to be checked on the server. The client can drop a message, that does not have a data.message.name field.

**Comment by FinnStutzenstein** [comment]
But this requires many changes in the client and diverges from the original protocol

**Comment by ostcar** [comment]
Ok. I add it in the next days

**Comment by FinnStutzenstein** [comment]
Thanks!
