### ISSUE TITLE
All data always send on connection start

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#35]
Hi,

If I reload the client, I always get an autoupdate with `all_data=True`. Example:

- The client is up to date with his changeid being 13.
- The client does a request. It gets the autoupdate for the newly created change id 14: `from_change_id=13` and `to_change_id=14`
- The client stores the new max change id 14.
- Reload. The client connects with `autoupdate?change_id=14`.
- It recieves an autoupdate with `from_change_id=0`, `to_change_id=14` and `all_data=true`. There shouldn't be an autoupdate since the client is up to date.

Another thing: In the OS3 server `from_change_id` and `to_change_id` are inclusive. The old behavoir would have send the following data in the second step: `from_change_id=14` and `to_change_id=14`. Luckily the client doesn't care about this, but maybe the autoupdate should be consistent.

**Comment by ostcar** [comment]
This was a typo like error. I fixed it in #37.

For the other thing. The `from_id` is just a fake. The server just returns the last change id. If you want, I can return `last change id + 1`.  If the client doesn't care about this, could I also remove the filed?
