### ISSUE TITLE
Support redis slaves

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#67]
Accept another redis instance that is read-only: Use the read-only redis for XREAD, ... and use the also-write redis for publishing notify messages.

**Comment by ostcar** [comment]
An alternative would be to use redis sentinel. We should first decide if we want to give sentinel a try before I fix this issue.

**Comment by FinnStutzenstein** [comment]
Gernot and I do not have the time to switch to redis sentinel. We used replication just for splitting read-and write load on redis, not for failure-safety. (Background: We experienced a major improvement when seperating heavy read tasks from the write instance: We ran into network throttling and write requests got heavily delayed resulting in gatewy timeouts. This was in 2018 and holds until now. I tested it again 2 month ago.)
