### ISSUE TITLE
Unify error messages

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#85]
Please make a list of possible errors returned. Is the format always `{"error": {"type": <type>, "msg": <msg>}}`?

Please unify `auth_required` and `ErrorAuth`.

**Comment by FinnStutzenstein** [comment]
@ostcar Ping. This is important, so I can catch auth errors in the client.

**Comment by ostcar** [comment]
This is fixed. Please test it and then close this issue.

Now, there are two types of errors send to the client:

```
{"error": {"type": "invalid_request", "msg": <msg>}}
{"error": {"type": "auth_required", "msg": <msg>}}
```

The message can be different. For example, with there "auth_required" the message can be: `Access for anonymous user is disabled` or `You have to be logged in to use the notify system.` or `You have to be logged in to send applause.`

The client should not parse the msg field. It is only for debugging or showing it the the user. The msg could be changed any time.
