### ISSUE TITLE
Applaus does not work with multiple users

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#88]
Please write a test for the applause system. Issuing two claps from two users result in `level=1`.

**Comment by FinnStutzenstein** [comment]
@tsiegleauq He has discovered the issue

**Comment by ostcar** [comment]
Found the problem. The reason was, that I removed old applause after one second. I changed this to one minute (applause older  `general_system_stream_applause_timeout` Seconds is not counted).

**Comment by FinnStutzenstein** [comment]
Maybe you can do something like `general_system_stream_applause_timeout*2` or so to keep it flexible
