### ISSUE TITLE
Send empty autoupdate on connection

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#96]
We need to seperate working and dangling connections. THe client can only check it, if it recieves something on connect. For notify and projector there is always an initial message when connecting. For the autoupdate this is not the case, if the client is up to date (change id). In this case an empty autoupdate is necessary to see, that the connection was successfully established. Please add a first empty autoupdate, if there is non for fresh connections.

**Comment by ostcar** [comment]
I do this in os4 but it is not so easy to implement in the code of this service.

Would it be ok if the service always sends a message after the connection is established? For example
```
{"connected": true}
```

**Comment by FinnStutzenstein** [comment]
This is ok

**Comment by ostcar** [comment]
@FinnStutzenstein there was a misunderstanding. I already merged it thereby broke the master. Can you add this feature to the client as soon as possible?
