### ISSUE TITLE
regression with commit e50116c001f12b4b0dbf1f5e0abba264943ad8ab

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides3-autoupdate-service#99]
commit e50116c001f12b4b0dbf1f5e0abba264943ad8ab introduced an urgent bug:

try to save a config (e.g. general) -> server restarts!

**Comment by ostcar** [comment]
Works for me.

Which service restarts? The autoupdate service or the python service?

Is there an error message?

Which commit do you use for the openslides service (python and client)

**Comment by ostcar** [comment]
@FinnStutzenstein this has to be fixed in the client

**Comment by FinnStutzenstein** [comment]
Yes and no. It seems, that someone has updated this service without testing. Also I wonder myself: In the master of OpenSlides commit b187dd439bd7456e105901ca96cd0995862d4419 is still tabbed. @emanuelschuetze How did you even test a newer commit? Also: How can the applause being merged without having the autoupdate service on at least c11398959b30bdb095b419f3c5785b1dd0b4e555? Someone screwed something up there...

**Comment by FinnStutzenstein** [comment]
As this is not a problem of the autoupdate service but rather than version management I'll close it here.
